#!/usr/bin/env python3
"""Generate per-scope services from config/scopes.yaml.

  scripts/gen-scopes.py compose  > compose.scopes.yaml
  scripts/gen-scopes.py k8s      # writes k8s/generated/ (per-scope manifests, Secret + ConfigMaps from config/)

Per scope: lightrag-<scope> (docs graph), falkordb-<scope> + codegraph-<scope> (code graph), indexer-<scope> (job).
Service/container names are identical in compose and Kubernetes, so the gateway and ingest need no changes.
"""
import re, sys, yaml, pathlib

cfg = yaml.safe_load(open(pathlib.Path(__file__).parent.parent / "config/scopes.yaml"))
scopes = cfg["scopes"]

def safe(name):  # LightRAG workspace: a-z A-Z 0-9 _
    return re.sub(r"[^A-Za-z0-9_]", "_", name)

LIGHTRAG_ENV = {
    "HOST": "0.0.0.0", "PORT": "9621", "WORKING_DIR": "/app/data/rag_storage", "INPUT_DIR": "/app/data/inputs",
    "LIGHTRAG_API_KEY": "${LIGHTRAG_API_KEY}",
    "LLM_BINDING": "${LLM_PROVIDER:-ollama}", "LLM_BINDING_HOST": "${LLM_BASE_URL:-http://ollama:11434}",
    "LLM_BINDING_API_KEY": "${LLM_API_KEY:-ollama}", "LLM_MODEL": "${LLM_MODEL}", "OLLAMA_LLM_NUM_CTX": "32768",
    "EMBEDDING_BINDING": "${EMBED_PROVIDER:-ollama}", "EMBEDDING_BINDING_HOST": "${EMBED_BASE_URL:-http://ollama:11434}",
    "EMBEDDING_BINDING_API_KEY": "${EMBED_API_KEY:-ollama}",
    "EMBEDDING_MODEL": "${EMBED_MODEL}", "EMBEDDING_DIM": "${EMBED_DIM}",
    "LLM_TIMEOUT": "600", "MAX_PARALLEL_INSERT": "2", "WHITELIST_PATHS": "/health",
    "LIGHTRAG_KV_STORAGE": "PGKVStorage", "LIGHTRAG_DOC_STATUS_STORAGE": "PGDocStatusStorage",
    "LIGHTRAG_VECTOR_STORAGE": "PGVectorStorage", "LIGHTRAG_GRAPH_STORAGE": "PGTableGraphStorage",
    "POSTGRES_HOST": "postgres", "POSTGRES_PORT": "5432", "POSTGRES_USER": "${POSTGRES_USER}",
    "POSTGRES_PASSWORD": "${POSTGRES_PASSWORD}", "POSTGRES_DATABASE": "lightrag", "POSTGRES_VECTOR_INDEX_TYPE": "HNSW",
}

def compose():
    services, volumes = {}, {}
    for name, sc in scopes.items():
        ws = safe(name)
        services[f"lightrag-{name}"] = {
            "image": "ghcr.io/hkuds/lightrag:v1.5.7", "restart": "unless-stopped",
            "depends_on": {"postgres": {"condition": "service_healthy"}},
            "environment": {**LIGHTRAG_ENV, "WORKSPACE": f"scope_{ws}"},
            "volumes": [f"lightrag_{ws}:/app/data"],
        }
        volumes[f"lightrag_{ws}"] = None
        services[f"falkordb-{name}"] = {
            "image": "docker.io/falkordb/falkordb:v4.20.4", "restart": "unless-stopped",
            "volumes": [f"falkordb_{ws}:/var/lib/falkordb/data"],
            "healthcheck": {"test": ["CMD", "redis-cli", "PING"], "interval": "10s", "timeout": "5s", "retries": 10},
        }
        volumes[f"falkordb_{ws}"] = None
        services[f"codegraph-{name}"] = {
            "build": "./mcp/codegraph-mcp", "restart": "unless-stopped",
            "depends_on": {f"falkordb-{name}": {"condition": "service_healthy"}},
            "environment": {"DEFAULT_DATABASE": "falkordb-remote", "FALKORDB_HOST": f"falkordb-{name}", "FALKORDB_PORT": "6379"},
            "volumes": [f"repos_{ws}:/workspace:ro", f"cgc_{ws}:/home/cgc/.codegraphcontext"],
        }
        volumes[f"repos_{ws}"] = None; volumes[f"cgc_{ws}"] = None
        services[f"indexer-{name}"] = {
            "build": "./mcp/codegraph-mcp", "profiles": ["jobs"],
            "depends_on": {f"falkordb-{name}": {"condition": "service_healthy"}},
            "environment": {"DEFAULT_DATABASE": "falkordb-remote", "FALKORDB_HOST": f"falkordb-{name}", "FALKORDB_PORT": "6379",
                            "GIT_DOC_REPOS": ",".join(sc.get("repos", [])), "GITHUB_TOKEN": "${GITHUB_TOKEN}"},
            "volumes": [f"repos_{ws}:/workspace", f"cgc_{ws}:/home/cgc/.codegraphcontext",
                        "./index/index-repo.sh:/usr/local/bin/index-repo.sh:ro"],
            "entrypoint": ["/bin/bash", "/usr/local/bin/index-repo.sh", "all"],
        }
    out = {"services": services, "volumes": volumes}
    print("# GENERATED by scripts/gen-scopes.py from config/scopes.yaml — do not edit by hand.\n"
          "# Use: docker compose -f compose.yaml -f compose.scopes.yaml up -d")
    print(yaml.safe_dump(out, sort_keys=False, width=120))

# Names the engines expect, derived from the short names in config/stack.env. Kubernetes has no ${VAR} interpolation
# for Secrets, so the generator materialises them into the stack-env Secret.
DERIVED_ENV = {
    "LLM_BINDING": "{LLM_PROVIDER}", "LLM_BINDING_HOST": "{LLM_BASE_URL}", "LLM_BINDING_API_KEY": "{LLM_API_KEY}",
    "EMBEDDING_BINDING": "{EMBED_PROVIDER}", "EMBEDDING_BINDING_HOST": "{EMBED_BASE_URL}",
    "EMBEDDING_BINDING_API_KEY": "{EMBED_API_KEY}", "EMBEDDING_MODEL": "{EMBED_MODEL}", "EMBEDDING_DIM": "{EMBED_DIM}",
    "HINDSIGHT_API_DATABASE_URL": "postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@postgres:5432/hindsight",
    "HINDSIGHT_API_LLM_PROVIDER": "{LLM_PROVIDER}", "HINDSIGHT_API_LLM_BASE_URL": "{LLM_BASE_URL}",
    "HINDSIGHT_API_LLM_MODEL": "{LLM_MODEL}", "HINDSIGHT_API_LLM_API_KEY": "{LLM_API_KEY}",
    "HINDSIGHT_API_EMBEDDINGS_OPENAI_BASE_URL": "{HINDSIGHT_EMBED_BASE_URL}",
    "HINDSIGHT_API_EMBEDDINGS_OPENAI_API_KEY": "{EMBED_API_KEY}",
    "HINDSIGHT_API_EMBEDDINGS_OPENAI_MODEL": "{EMBED_MODEL}", "HINDSIGHT_API_EMBEDDINGS_OPENAI_DIMENSIONS": "{EMBED_DIM}",
    "HINDSIGHT_API_RERANKER_PROVIDER": "{HINDSIGHT_RERANKER}",
    "HINDSIGHT_API_TENANT_API_KEY": "{HINDSIGHT_API_KEY}", "HINDSIGHT_CP_DATAPLANE_API_KEY": "{HINDSIGHT_API_KEY}",
    "DATABASE_URL": "postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@postgres:5432/sourcebot",
    "AUTH_URL": "{SOURCEBOT_AUTH_URL}", "AUTH_SECRET": "{SOURCEBOT_AUTH_SECRET}",
}

def load_env() -> dict | None:
    """config/stack.env plus the derived engine-specific names (DERIVED_ENV). None when the file does not exist."""
    src = pathlib.Path(__file__).parent.parent / "config/stack.env"
    if not src.exists():
        return None
    base = {}
    for line in src.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1); base[k.strip()] = v.strip()
    for k, v in {"LLM_PROVIDER": "ollama", "LLM_BASE_URL": "http://ollama:11434", "LLM_API_KEY": "ollama",
                 "EMBED_PROVIDER": "ollama", "EMBED_BASE_URL": "http://ollama:11434", "EMBED_API_KEY": "ollama",
                 "HINDSIGHT_EMBED_BASE_URL": "http://ollama:11434/v1", "HINDSIGHT_RERANKER": "local"}.items():
        base.setdefault(k, v)
    class _D(dict):
        def __missing__(self, k): return ""
    return {**base, **{k: v.format_map(_D(base)) for k, v in DERIVED_ENV.items()}}


def k8s():
    """k8s/generated/: per-scope manifests + kustomization with Secret (from config/stack.env) and ConfigMaps (from config/)."""
    root = pathlib.Path(__file__).parent.parent
    out = root / "k8s/generated"
    out.mkdir(parents=True, exist_ok=True)
    for f in out.glob("*"):
        f.unlink()
    env = load_env()
    if env is None:
        sys.exit("error: config/stack.env not found (copy config/stack.env.example first)")
    (out / "stack-env.env").write_text("".join(f"{k}={v}\n" for k, v in env.items()))
    (out / "stack-env.env").chmod(0o600)
    for name, src in {"scopes.yaml": "config/scopes.yaml", "config.json": "config/sourcebot/config.json",
                      "init.sql": "config/postgres/init.sql"}.items():
        (out / name).write_text((root / src).read_text())
    lightrag_env = {k: (v if not v.startswith("${") else None) for k, v in LIGHTRAG_ENV.items()}
    resources = []
    for name, sc in scopes.items():
        ws = safe(name)
        env_lines = "\n".join(f"            - {{ name: {k}, value: \"{v}\" }}" for k, v in lightrag_env.items() if v is not None)
        repos = ",".join(sc.get("repos", []))
        (out / f"scope-{name}.yaml").write_text(f"""# GENERATED by scripts/gen-scopes.py k8s for scope "{name}" -- do not edit.
apiVersion: v1
kind: Service
metadata: {{ name: lightrag-{name}, labels: {{ scope: {name} }} }}
spec:
  selector: {{ app: lightrag-{name} }}
  ports: [{{ port: 9621, targetPort: 9621 }}]
---
apiVersion: apps/v1
kind: Deployment
metadata: {{ name: lightrag-{name}, labels: {{ scope: {name} }} }}
spec:
  replicas: 1
  strategy: {{ type: Recreate }}
  selector: {{ matchLabels: {{ app: lightrag-{name} }} }}
  template:
    metadata: {{ labels: {{ app: lightrag-{name}, scope: {name} }} }}
    spec:
      containers:
        - name: lightrag
          image: ghcr.io/hkuds/lightrag:v1.5.7
          envFrom: [{{ secretRef: {{ name: stack-env }} }}]   # LLM_BINDING*, EMBEDDING_*, POSTGRES_*, LIGHTRAG_API_KEY
          env:
{env_lines}
            - {{ name: WORKSPACE, value: scope_{ws} }}
          ports: [{{ containerPort: 9621 }}]
          volumeMounts: [{{ name: data, mountPath: /app/data }}]
          readinessProbe:
            httpGet: {{ path: /health, port: 9621 }}
            initialDelaySeconds: 20
            periodSeconds: 15
      volumes:
        - name: data
          persistentVolumeClaim: {{ claimName: lightrag-{name}-data }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {{ name: lightrag-{name}-data }}
spec: {{ accessModes: [ReadWriteOnce], resources: {{ requests: {{ storage: 5Gi }} }} }}
---
apiVersion: v1
kind: Service
metadata: {{ name: falkordb-{name}, labels: {{ scope: {name} }} }}
spec:
  selector: {{ app: falkordb-{name} }}
  ports: [{{ port: 6379, targetPort: 6379 }}]
---
apiVersion: apps/v1
kind: StatefulSet
metadata: {{ name: falkordb-{name}, labels: {{ scope: {name} }} }}
spec:
  serviceName: falkordb-{name}
  replicas: 1
  selector: {{ matchLabels: {{ app: falkordb-{name} }} }}
  template:
    metadata: {{ labels: {{ app: falkordb-{name}, scope: {name} }} }}
    spec:
      containers:
        - name: falkordb
          image: docker.io/falkordb/falkordb:v4.20.4
          ports: [{{ containerPort: 6379 }}]
          volumeMounts: [{{ name: data, mountPath: /var/lib/falkordb/data }}]
          readinessProbe:
            exec: {{ command: ["redis-cli", "PING"] }}
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata: {{ name: data }}
      spec: {{ accessModes: [ReadWriteOnce], resources: {{ requests: {{ storage: 5Gi }} }} }}
---
apiVersion: v1
kind: Service
metadata: {{ name: codegraph-{name}, labels: {{ scope: {name} }} }}
spec:
  selector: {{ app: codegraph-{name} }}
  ports: [{{ port: 8045, targetPort: 8045 }}]
---
apiVersion: apps/v1
kind: Deployment
metadata: {{ name: codegraph-{name}, labels: {{ scope: {name} }} }}
spec:
  replicas: 1
  strategy: {{ type: Recreate }}
  selector: {{ matchLabels: {{ app: codegraph-{name} }} }}
  template:
    metadata: {{ labels: {{ app: codegraph-{name}, scope: {name} }} }}
    spec:
      containers:
        - name: codegraph
          image: agent-context-stack-codegraph-public:latest
          imagePullPolicy: IfNotPresent
          env:
            - {{ name: DEFAULT_DATABASE, value: falkordb-remote }}
            - {{ name: FALKORDB_HOST, value: falkordb-{name} }}
            - {{ name: FALKORDB_PORT, value: "6379" }}
          ports: [{{ containerPort: 8045 }}]
          volumeMounts:
            - {{ name: repos, mountPath: /workspace, readOnly: true }}
            - {{ name: cgc, mountPath: /home/cgc/.codegraphcontext }}
      volumes:
        - name: repos
          persistentVolumeClaim: {{ claimName: repos-{name} }}
        - name: cgc
          persistentVolumeClaim: {{ claimName: cgc-{name} }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {{ name: repos-{name} }}
spec: {{ accessModes: [ReadWriteOnce], resources: {{ requests: {{ storage: 10Gi }} }} }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {{ name: cgc-{name} }}
spec: {{ accessModes: [ReadWriteOnce], resources: {{ requests: {{ storage: 1Gi }} }} }}
---
# Nightly re-index. One-off run:  kubectl -n context-stack create job --from=cronjob/indexer-{name} indexer-{name}-now
apiVersion: batch/v1
kind: CronJob
metadata: {{ name: indexer-{name}, labels: {{ scope: {name} }} }}
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata: {{ labels: {{ app: indexer-{name}, scope: {name} }} }}
        spec:
          restartPolicy: Never
          containers:
            - name: indexer
              image: agent-context-stack-codegraph-public:latest
              imagePullPolicy: IfNotPresent
              command: ["/bin/bash", "/usr/local/bin/index-repo.sh", "all"]
              envFrom: [{{ secretRef: {{ name: stack-env }} }}]   # GITHUB_TOKEN for private repos
              env:
                - {{ name: DEFAULT_DATABASE, value: falkordb-remote }}
                - {{ name: FALKORDB_HOST, value: falkordb-{name} }}
                - {{ name: FALKORDB_PORT, value: "6379" }}
                - {{ name: GIT_DOC_REPOS, value: "{repos}" }}
              volumeMounts:
                - {{ name: repos, mountPath: /workspace }}
                - {{ name: cgc, mountPath: /home/cgc/.codegraphcontext }}
                - {{ name: script, mountPath: /usr/local/bin/index-repo.sh, subPath: index-repo.sh, readOnly: true }}
          volumes:
            - name: repos
              persistentVolumeClaim: {{ claimName: repos-{name} }}
            - name: cgc
              persistentVolumeClaim: {{ claimName: cgc-{name} }}
            - name: script
              configMap: {{ name: index-script, defaultMode: 0o755 }}
""")
        resources.append(f"scope-{name}.yaml")
    (out / "index-repo.sh").write_text((root / "index/index-repo.sh").read_text())
    (out / "kustomization.yaml").write_text("""# GENERATED by scripts/gen-scopes.py k8s -- do not edit, do not commit.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
""" + "".join(f"  - {r}\n" for r in resources) + """secretGenerator:
  - name: stack-env
    envs: [stack-env.env]
configMapGenerator:
  - name: scopes-config
    files: [scopes.yaml]
  - name: sourcebot-config
    files: [config.json]
  - name: postgres-init
    files: [init.sql]
  - name: index-script
    files: [index-repo.sh]
generatorOptions:
  disableNameSuffixHash: true
""")
    print(f"wrote k8s/generated for scopes: {', '.join(scopes)}")


{"compose": compose, "k8s": k8s}[sys.argv[1]]()
