#!/usr/bin/env python3
"""Generate per-scope services from config/scopes.yaml.

  scripts/gen-scopes.py compose  > compose.scopes.yaml
  scripts/gen-scopes.py quadlet  # writes quadlet/scope-*.container files

Per scope: lightrag-<scope> (docs graph), falkordb-<scope> + codegraph-<scope> (code graph), indexer-<scope> (job).
"""
import re, sys, yaml, pathlib

cfg = yaml.safe_load(open(pathlib.Path(__file__).parent.parent / "config/scopes.yaml"))
scopes = cfg["scopes"]

def safe(name):  # LightRAG workspace: a-z A-Z 0-9 _
    return re.sub(r"[^A-Za-z0-9_]", "_", name)

LIGHTRAG_ENV = {
    "HOST": "0.0.0.0", "PORT": "9621", "WORKING_DIR": "/app/data/rag_storage", "INPUT_DIR": "/app/data/inputs",
    "LIGHTRAG_API_KEY": "${LIGHTRAG_API_KEY}",
    "LLM_BINDING": "ollama", "LLM_BINDING_HOST": "http://ollama:11434", "LLM_MODEL": "${LLM_MODEL}", "OLLAMA_LLM_NUM_CTX": "32768",
    "EMBEDDING_BINDING": "ollama", "EMBEDDING_BINDING_HOST": "http://ollama:11434",
    "EMBEDDING_MODEL": "${EMBED_MODEL}", "EMBEDDING_DIM": "${EMBED_DIM}",
    "LIGHTRAG_KV_STORAGE": "PGKVStorage", "LIGHTRAG_DOC_STATUS_STORAGE": "PGDocStatusStorage",
    "LIGHTRAG_VECTOR_STORAGE": "PGVectorStorage", "LIGHTRAG_GRAPH_STORAGE": "PGTableGraphStorage",
    "POSTGRES_HOST": "postgres", "POSTGRES_PORT": "5432", "POSTGRES_USER": "${POSTGRES_USER}",
    "POSTGRES_PASSWORD": "${POSTGRES_PASSWORD}", "POSTGRES_DATABASE": "lightrag", "POSTGRES_VECTOR_INDEX_TYPE": "HNSW",
}

def compose():
    services, volumes = {}, {}
    for name, sc in scopes.items():
        ws = safe(name)
        services[f"lightrag-{name}"] = {
            "image": "ghcr.io/hkuds/lightrag:latest", "restart": "unless-stopped",
            "depends_on": {"postgres": {"condition": "service_healthy"}, "ollama": {"condition": "service_started"}},
            "environment": {**LIGHTRAG_ENV, "WORKSPACE": f"scope_{ws}"},
            "volumes": [f"lightrag_{ws}:/app/data"],
        }
        volumes[f"lightrag_{ws}"] = None
        services[f"falkordb-{name}"] = {
            "image": "docker.io/falkordb/falkordb:latest", "restart": "unless-stopped",
            "volumes": [f"falkordb_{ws}:/var/lib/falkordb/data"],
            "healthcheck": {"test": ["CMD", "redis-cli", "PING"], "interval": "10s", "timeout": "5s", "retries": 10},
        }
        volumes[f"falkordb_{ws}"] = None
        services[f"codegraph-{name}"] = {
            "build": "./mcp/codegraph-mcp", "restart": "unless-stopped",
            "depends_on": {f"falkordb-{name}": {"condition": "service_healthy"}},
            "environment": {"DEFAULT_DATABASE": "falkordb", "FALKORDB_HOST": f"falkordb-{name}", "FALKORDB_PORT": "6379"},
            "volumes": [f"repos_{ws}:/workspace:ro", f"cgc_{ws}:/home/cgc/.codegraphcontext"],
        }
        volumes[f"repos_{ws}"] = None; volumes[f"cgc_{ws}"] = None
        services[f"indexer-{name}"] = {
            "build": "./mcp/codegraph-mcp", "profiles": ["jobs"],
            "depends_on": {f"falkordb-{name}": {"condition": "service_healthy"}},
            "environment": {"DEFAULT_DATABASE": "falkordb", "FALKORDB_HOST": f"falkordb-{name}", "FALKORDB_PORT": "6379",
                            "GIT_DOC_REPOS": ",".join(sc.get("repos", [])), "GITHUB_TOKEN": "${GITHUB_TOKEN}"},
            "volumes": [f"repos_{ws}:/workspace", f"cgc_{ws}:/home/cgc/.codegraphcontext",
                        "./index/index-repo.sh:/usr/local/bin/index-repo.sh:ro"],
            "entrypoint": ["/bin/bash", "/usr/local/bin/index-repo.sh", "all"],
        }
    out = {"services": services, "volumes": volumes}
    print("# GENERATED by scripts/gen-scopes.py from config/scopes.yaml — do not edit by hand.\n"
          "# Use: docker compose -f compose.yaml -f compose.scopes.yaml up -d")
    print(yaml.safe_dump(out, sort_keys=False, width=120))

def quadlet():
    qd = pathlib.Path(__file__).parent.parent / "quadlet"
    for f in qd.glob("scope-*"):
        f.unlink()
    for name, sc in scopes.items():
        ws = safe(name)
        env = "\n".join(f"Environment={k}={v}" for k, v in {**LIGHTRAG_ENV, "WORKSPACE": f"scope_{ws}"}.items()
                        if not v.startswith("${"))
        (qd / f"scope-{name}-lightrag.container").write_text(f"""[Unit]
Description=LightRAG docs graph for scope {name}
Requires=postgres.service ollama.service
After=postgres.service ollama.service

[Container]
Image=ghcr.io/hkuds/lightrag:latest
ContainerName=lightrag-{name}
Network=stack.network
Volume=stack-lightrag-{ws}:/app/data
EnvironmentFile=%h/agent-context-stack/.env
{env}
Environment=LLM_MODEL=${{LLM_MODEL}} EMBEDDING_MODEL=${{EMBED_MODEL}} EMBEDDING_DIM=${{EMBED_DIM}}
Environment=POSTGRES_USER=${{POSTGRES_USER}} POSTGRES_PASSWORD=${{POSTGRES_PASSWORD}}

[Service]
Restart=always

[Install]
WantedBy=default.target
""")
        (qd / f"scope-{name}-falkordb.container").write_text(f"""[Unit]
Description=FalkorDB for scope {name}

[Container]
Image=docker.io/falkordb/falkordb:latest
ContainerName=falkordb-{name}
Network=stack.network
Volume=stack-falkordb-{ws}:/var/lib/falkordb/data
HealthCmd=redis-cli PING

[Service]
Restart=always

[Install]
WantedBy=default.target
""")
        (qd / f"scope-{name}-codegraph.container").write_text(f"""[Unit]
Description=CodeGraphContext MCP for scope {name}
Requires=scope-{name}-falkordb.service
After=scope-{name}-falkordb.service

[Container]
Image=localhost/stack-codegraph-mcp:latest
ContainerName=codegraph-{name}
Network=stack.network
Volume=stack-repos-{ws}:/workspace:ro
Volume=stack-cgc-{ws}:/home/cgc/.codegraphcontext
Environment=DEFAULT_DATABASE=falkordb FALKORDB_HOST=falkordb-{name} FALKORDB_PORT=6379

[Service]
Restart=always

[Install]
WantedBy=default.target
""")
        (qd / f"scope-{name}-indexer.container").write_text(f"""[Unit]
Description=Index repos for scope {name}
Requires=scope-{name}-falkordb.service
After=scope-{name}-falkordb.service

[Container]
Image=localhost/stack-codegraph-mcp:latest
ContainerName=indexer-{name}
Network=stack.network
Volume=stack-repos-{ws}:/workspace
Volume=stack-cgc-{ws}:/home/cgc/.codegraphcontext
Volume=%h/agent-context-stack/index/index-repo.sh:/usr/local/bin/index-repo.sh:ro,Z
EnvironmentFile=%h/agent-context-stack/.env
Environment=DEFAULT_DATABASE=falkordb FALKORDB_HOST=falkordb-{name} FALKORDB_PORT=6379
Environment=GIT_DOC_REPOS={",".join(sc.get("repos", []))}
Entrypoint=/bin/bash
Exec=/usr/local/bin/index-repo.sh all

[Service]
Type=oneshot
""")
        (qd / f"scope-{name}-indexer.timer").write_text(f"""[Unit]
Description=Nightly re-index for scope {name}

[Timer]
OnCalendar=*-*-* 03:00:00
Persistent=true

[Install]
WantedBy=timers.target
""")
    print(f"wrote quadlet units for scopes: {', '.join(scopes)}")

{"compose": compose, "quadlet": quadlet}[sys.argv[1]]()
